en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Strong Towns Halifax. All Rights Reserved. [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "Strong Towns Halifax"
  description: "Strong Towns Halifax promotes financially strong communities via smart urban planning: walkable neighborhoods, cycling, and transit for vibrant cities"
  params:
    ### calls to action ###
    main_cta:
      text: "Get involved"
      link: "/join/"
    footer_cta:
      text: "Get involved"
      link: "/join/"
    github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: "About"
      url: "#"
      weight: 1
    - identifier: "strong-towns-hfx"
      name: "Strong Towns Halifax"
      url: "/about/strong-towns-halifax"
      weight: 1
      post: "What is Strong Towns Halifax?"
      parent: "about"
    - identifier: "strong-towns"
      name: "Strong Towns"
      url: "/about/strong-towns"
      weight: 2
      post: "What is the non profit Strong Towns."
      parent: "about"
    - identifier: "projects"
      name: "Projects"
      url: "/example-page/"
      weight: 2
    - identifier: "start-up"
      name: "Build up"
      url: "/projects/start-up"
      weight: 1
      post: "Building up Strong Towns Halifax"
      parent: "projects"
    - identifier: "events"
      name: "Events"
      url: "/events/"
      weight: 4
    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 5
    - identifier: "contact"
      name: "Contact"
      url: "/contact/"
      weight: 6
