######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
logo_on_white: "/STH-black.png"
logo_on_black: "/STH-white.png"
custom_js: []
custom_css: []

######################## custom config ####################

### default social share image (can also be set per lang) ###
images: ["/img/social-share.png"]

github:
  repo_url: "https://github.com/Strong-Towns-Halifax/webSTH"
  show_edit_link: false

social_links:
  devstats: ""
  discord: "https://discord.gg/YGUTDTmshP"
  facebook: ""
  flickr: ""
  github: "https://github.com/Strong-Towns-Halifax"
  instagram: "https://www.instagram.com/strongtownshfx/"
  landscape: ""
  linkedin: "https://www.linkedin.com/company/96921269/"
  mastodon: ""
  pinterest: ""
  rss: ""
  slack: ""
  stackoverflow: ""
  threads: ""
  twitter: "https://twitter.com/strongtownshali"
  x: ""
  youtube: ""

# Makes the header sticky on tall screens
sticky_header: true
# Enable search in header UI
show_search: false
